<!doctype html public "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <title>Cherokee Web Server: Administration</title>
    %%header%%
    <link rel="stylesheet" href="theme/cherokee.css" type="text/css" />
  </head>
  <body>
    <div id="container">
        <div id="header">
            <div id="info">
                Version 0.7.3
            </div>
        </div>
        <div id="bar">
		    %%menu%%
        </div>
        <div id="main">
          <h1>%%pagetitle%%</h1>
	   </div>

	   

        %%body%%

        <div class="clearfix"></div>
        <div id="footer" class="clearfix">
          Website: <a href="http://0x50.org">http://0x50.org</a><br/>
          Mailing Lists: <a href="http://www.0x50.org/cgi-bin/mailman/listinfo/cherokee">Cherokee Mailing List</a><br/>
          &copy; Alvaro Lopez Ortega
        </div>
    </div>
  </body>
</html>
