.TH cherokee-admin-launcher 8 "February 16, 2011"
.SH NAME
cherokee-admin-launcher - Easy launcher for Cherokee's administrative interface
.SH SYNOPSIS
.B cherokee-admin-launcher [options]
.SH DESCRIPTION
\fIcherokee-admin-launcher\fP is part of Cherokee, an extremely fast,
flexible and embeddable web server. It is used as a wrapper for the
main administrative interface used to configure Cherokee. This
executable is meant to be called from a desktop launcher,
automatically accessing an authenticated web browser session of the
administration interface.
.SH SEE ALSO
This program is a part of the Cherokee web server,
\&\fIcherokee\fR\|(1). It wraps the main \&\fIcherokee-admin\fR\|(1)
binary and accepts all its parameters.
.SH AUTHOR
This manual page was written by Taher Shihadeh <taher@unixwars.com>, for
the Debian GNU/linux system (but may be used by others).
.PP
Cherokee itself was written by Álvaro López Ortega
<alvaro@alobbs.com>.
