.TH cherokee-admin 8 "July 28, 2008"
.SH NAME
cherokee-admin - Runs Cherokee's administrative interface
.SH SYNOPSIS
.B cherokee-admin
[\-d DIR] [\-p PORT] [\-C FILE] [\-b]
.SH DESCRIPTION
\fIcherokee-admin\fP runs the server for the administrative interface
used to configure Cherokee. The interface itself will be available via
your Web browser.
.SH OPTIONS
\fIcherokee-admin\fP accepts the following options:
.TP 8
.B  \-h, --help
Shows brief usage information
.TP 8
.B  \-V, --version
Show version and exit
.TP 8
.B  \-x, --debug
Print the backend errors to the terminal where it is executing. If
omited, this debug information is lost.
.TP 8
.B  \-b, --bind[=IP]
By default \fIcherokee-admin\fP binds only to 127.0.0.1 (localhost), which
means you can only connect to it from the same system. With this parameter
you can specify the network address to listen to. If no IP is provided,
it will bind to all interfaces.
.TP 8
.B  \-C, --target=PATH
Requests a configuration file different than the default
/etc/cherokee/cherokee.conf to be used
.TP 8
.B  \-d, --appdir=DIR
Uses a custom admin-interface path
.TP 8
.B \-p, --port=NUM
Specifies an alternative port. By default, 9090.
.SH SEE ALSO
This program is a part of the Cherokee web server, \&\fIcherokee\fR\|(1)
.SH AUTHOR
This manual page was written by Gunnar Wolf <gwolf@debian.org>, for
the Debian GNU/linux system (but may be used by others). Maintainted by
Taher Shihadeh <taher@unixwars.com>
.PP
Cherokee itself was written by Álvaro López Ortega
<alvaro@alobbs.com>.
