echo Port 80                              > "%CD%\cherokee.conf"
echo DocumentRoot "%CD%\www\"            >> "%CD%\cherokee.conf"
echo.                                    >> "%CD%\cherokee.conf"
echo DirectoryIndex index.html           >> "%CD%\cherokee.conf"
echo.                                    >> "%CD%\cherokee.conf"
echo Directory / {                       >> "%CD%\cherokee.conf"
echo    Handler common                   >> "%CD%\cherokee.conf"
echo }                                   >> "%CD%\cherokee.conf"
echo Directory /images {                 >> "%CD%\cherokee.conf"
echo    Handler file                     >> "%CD%\cherokee.conf"
echo }                                   >> "%CD%\cherokee.conf"
echo Extension php {                     >> "%CD%\cherokee.conf"
echo    Handler phpcgi {                 >> "%CD%\cherokee.conf"
echo      Interpreter C:\PHP\php-cgi.exe >> "%CD%\cherokee.conf"
echo    }                                >> "%CD%\cherokee.conf"
echo }                                   >> "%CD%\cherokee.conf"

echo @echo off                                                     > "%CD%\cherokee.bat"
echo cd "%CD%"                                                    >> "%CD%\cherokee.bat"
echo start "Cherokee" /min .\cherokee.exe -C "%CD%\cherokee.conf" >> "%CD%\cherokee.bat"
echo.                                                             >> "%CD%\cherokee.bat"
 
