#! /bin/sh
#
# Copyright (C) 2001-2014 Alvaro Lopez Ortega
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

TITLE="Root password required"
EXPLANATION="Please, provide the root password. Cherokee-admin requires system privileges."

DIALOG="display dialog \"$EXPLANATION\""
DIALOG="$DIALOG default answer \"\" "
DIALOG="$DIALOG buttons {\"Cancel\", \"OK\"} "
DIALOG="$DIALOG default button \"OK\" "
DIALOG="$DIALOG with title \"$TITLE\" "
DIALOG="$DIALOG with icon note "
DIALOG="$DIALOG with hidden answer"

result=`osascript -e 'tell application "Finder"' -e "activate" -e "$DIALOG" -e 'end tell'`
if [ "$result" = "" ]; then
    exit 1
else
    echo "$result" | sed -e 's/^text returned://' -e 's/, button returned:.*$//'
    exit 0
fi
