.\"                              hey, Emacs:   -*- nroff -*-
.\" cherokee is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation version 2 of the License.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH Cget 1 "March 31, 2008"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cget \- Cherokee web downloader
.SH SYNOPSIS
.B cget [options] URL
.SH DESCRIPTION
\fBcget\fP is a web downloading tool
.\" .PP
.\" It also...
.SH OPTIONS
No option is mandatory. By default the web is downloaded but it is not saved. 
If that is not the desired behavior it must be specified explicitly. 
Below is a summary of the
.B cget
options.
.PP
Startup:
.TP
.B -V,  --version                
Display version of currently installed cget and exit.
.TP
.B -h,  --help
Display help screen with common options.
.TP
.B    
Logging and input file:
.TP
.B -q,  --quiet
Run in quiet mode: no output is displayed.
.PP
Download:
.TP
.B -O, --output-document=FILE
Writes whatever document is downloaded to FILE
.PP	
HTTP options:
.TP
.B -s, --save-headers
This option saves HTTP headers to the file being saved (specified with -O option)
.TP
.B --header=STRING
this option inserts STRING among the headers sent in the HTTP request.
.SH EXAMPLE
cget http://www.cherokee-project.com/
.SH BUGS
.SS Bug reports
I would appreciate hearing of any problems you have with Cherokee.  I
would also like to hear from you if you have successfully used Cherokee,
especially if you are using it for a distribution.
.PP
There is a mailing list for discussion among Cherokee users and for
announcements of new and test versions. To join, send a message to
cherokee-admin@alobbs.com with the line:
.PP
.B subscribe cherokee
.PP
in the body of the message. The submission address is cherokee@alobbs.com.
.\" .SH "SEE ALSO"
.SH AUTHOR
Alvaro Lopez Ortega <alvaro@alobbs.com>. Manual page updated by Taher Shihadeh <taher@unixwars.com>.
